### ISSUE TITLE
Discrepancy between RNA graph trends

### ISSUE THREAD

**Issue by tdamsma** [realrolfje/coronadata#1]
First of all, thanks for providing this great dashboard! I was looking today and couldn't understand the big trend difference between the two graphs (highlighted in red) as they are based on the same source data. Can you explain that? 

![image](https://user-images.githubusercontent.com/7870803/108065801-d18f5380-705e-11eb-9649-f46ec2265424.png)

**Comment by realrolfje** [comment]
Hello Thijs, thanks for noticing. The strange estimate is something that I find surprising too. The calculation is explained here: https://realrolfje.github.io/coronadata/zieken.html (you can also get there by clicking on the first graph).

The blue line is based on the sewege data per region, multiplied by the inhabitants of that region. This way the areas with denser population weigh higher in the estimate of number of ill people (which makes sense to me).

The only explanation for this strange difference between the average and the estimated number of sick people is that the RNA per ml in regions with many people is high, and the the RNA per ml in other regions low. As you can see the sewege data has a lot of noise on it, apparently it is a measurement that is hard to do.

I think I need to come up with a different way of estimating or averaging per safety region, so that the noise in the sewage data does not affect the estimate this much, and in such a strange way.
